Load vault secrets from environment less stores or which are not written by dynaconf
rochacbruno/dynaconf pull request #725
Opened 2022-03-09 13:59 UTC by jyejare

TO BE ADDED

2022-03-09 15:16 UTC, rochacbruno requested changes

2022-03-09 15:16 UTC, rochacbruno commented on dynaconf/default_settings.py
> +MAIN_ENV_FOR_DYNACONF = get("MAIN_ENVIRONMENTS_FOR_DYNACONF", "MAIN")
```suggestion
MAIN_ENVIRONMENT_FOR_DYNACONF = get("MAIN_ENVIRONMENT_FOR_DYNACONF", "MAIN")
```

2022-03-09 15:16 UTC, rochacbruno commented on dynaconf/loaders/vault_loader.py
> +        env_list = [obj.MAIN_ENV_FOR_DYNACONF.lower(), ""]
```suggestion
        env_list = [obj.MAIN_ENVIRONMENT_FOR_DYNACONF.lower(), ""]
```

2022-03-09 18:22 UTC, jyejare reviewed
Fixed Comments !

2022-03-17 08:25 UTC, jyejare commented
Ping @rochacbruno , Need to get this in as we are blocked! Are you good with the changes or would you want to add changes in Doc and Version Doc ?

2022-03-17 11:34 UTC, rochacbruno commented
@jyejare some of the ci tests are not passing I was not able to verify yet the reason

2022-03-17 15:47 UTC, jyejare commented
@rochacbruno I hope that's not related to this change, but I can take a look! I didnt observe it first as all the ticks looked green.

2022-03-30 18:39 UTC, jyejare commented
@rochacbruno Fixed tests failing ! Please revisit .

2022-03-30 20:25 UTC, rochacbruno commented
Ci is broken, not related to your PR, I will test locally and if pass I will merge

2022-03-30 20:34 UTC, merged

2022-03-31 06:37 UTC, jyejare commented
@rochacbruno Sorry, in my last comment, I wanted to say "failing tests passed, please revisit", but said "ulta" :)

2022-04-12 12:55 UTC, jyejare commented
@rochacbruno Whats the plan on releasing a new version of dynaConf with this change? Is it sooner or can you release it soon for us ?

2022-04-12 13:43 UTC, jyejare commented
@rochacbruno That's good news for us !! Thanks :)